config/routes.rb
Rails.application.routes.draw do
  resources :series
  resources :chapters
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  include CalculatesDuration
  belongs_to :series, optional: true,class_name: "Series"

  serialize :duration, DurationCoder

  updates_duration_of :series
end

app/models/concerns/calculates_duration.rb
module CalculatesDuration
  extend ActiveSupport::Concern

  included do
    after_save_commit :update_parent_duration

    cattr_accessor :parent_to_update, :duration_association, :duration_column
  end

  class_methods do
    def calculates_duration_from(association_name, column: :duration)
      self.duration_association = association_name
      self.duration_column = column
    end

    def updates_duration_of(parent_association)
      self.parent_to_update = parent_association
    end
  end

  def update_duration!
    update(duration: calculate_duration)
  end

  def calculate_duration
    send(self.class.duration_association).sum(self.class.duration_column)
  end

  def update_parent_duration
    send(parent_association_name).update_duration! if has_parent_record?
  end

  def parent_association_name
    self.class.parent_to_update
  end

  def has_parent_record?
    !!send(parent_association_name) if parent_association_name
  end
end

app/models/duration_coder.rb
class DurationCoder
    def self.dump(value)
        return unless value
        value.to_i 
    end 

    def self.load(value) 
        return unless value
        ActiveSupport::Duration.build(value) 
    end 
    
end

app/models/series.rb
class Series < ApplicationRecord
include CalculatesDuration
has_many :chapters, dependent: :destroy, class_name: "Chapter"

serialize :duration, DurationCoder

calculates_duration_of :chapters
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :set_chapter, only: %i[ show edit update destroy ]

  # GET /chapters or /chapters.json
  def index
    @chapters = Chapter.all
  end

  # GET /chapters/1 or /chapters/1.json
  def show
  end

  # GET /chapters/new
  def new
    @chapter = Chapter.new
  end

  # GET /chapters/1/edit
  def edit
  end

  # POST /chapters or /chapters.json
  def create
    @chapter = Chapter.new(chapter_params)

    respond_to do |format|
      if @chapter.save
        format.html { redirect_to chapter_url(@chapter), notice: "Chapter was successfully created." }
        format.json { render :show, status: :created, location: @chapter }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chapters/1 or /chapters/1.json
  def update
    respond_to do |format|
      if @chapter.update(chapter_params)
        format.html { redirect_to chapter_url(@chapter), notice: "Chapter was successfully updated." }
        format.json { render :show, status: :ok, location: @chapter }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chapters/1 or /chapters/1.json
  def destroy
    @chapter.destroy

    respond_to do |format|
      format.html { redirect_to chapters_url, notice: "Chapter was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chapter
      @chapter = Chapter.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def chapter_params
      params.require(:chapter).permit(:title, :duration, :series_id)
    end
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  before_action :set_series, only: %i[ show edit update destroy ]

  # GET /series or /series.json
  def index
    @series = Series.all
  end

  # GET /series/1 or /series/1.json
  def show
  end

  # GET /series/new
  def new
    @series = Series.new
  end

  # GET /series/1/edit
  def edit
  end

  # POST /series or /series.json
  def create
    @series = Series.new(series_params)

    respond_to do |format|
      if @series.save
        format.html { redirect_to series_url(@series), notice: "Series was successfully created." }
        format.json { render :show, status: :created, location: @series }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /series/1 or /series/1.json
  def update
    respond_to do |format|
      if @series.update(series_params)
        format.html { redirect_to series_url(@series), notice: "Series was successfully updated." }
        format.json { render :show, status: :ok, location: @series }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /series/1 or /series/1.json
  def destroy
    @series.destroy

    respond_to do |format|
      format.html { redirect_to series_index_url, notice: "Series was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_series
      @series = Series.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def series_params
      params.require(:series).permit(:title, :duration)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/chapters/_chapter.html.erb
<div id="<%= dom_id chapter %>">
  <p>
    <strong>Title:</strong>
    <%= chapter.title %>
  </p>

  <p>
    <strong>Duration:</strong>
    <%= chapter.duration %>
  </p>

  <p>
    <strong>Series:</strong>
    <%= chapter.series_id %>
  </p>

</div>

app/views/chapters/_form.html.erb
<%= form_with(model: chapter) do |form| %>
  <% if chapter.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(chapter.errors.count, "error") %> prohibited this chapter from being saved:</h2>

      <ul>
        <% chapter.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :duration, style: "display: block" %>
    <%= form.number_field :duration %>
  </div>

  <div>
    <%= form.label :series_id, style: "display: block" %>
    <%= form.text_field :series_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/chapters/edit.html.erb
<h1>Editing chapter</h1>

<%= render "form", chapter: @chapter %>

<br>

<div>
  <%= link_to "Show this chapter", @chapter %> |
  <%= link_to "Back to chapters", chapters_path %>
</div>

app/views/chapters/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Chapters</h1>

<div id="chapters">
  <% @chapters.each do |chapter| %>
    <%= render chapter %>
    <p>
      <%= link_to "Show this chapter", chapter %>
    </p>
  <% end %>
</div>

<%= link_to "New chapter", new_chapter_path %>

app/views/chapters/new.html.erb
<h1>New chapter</h1>

<%= render "form", chapter: @chapter %>

<br>

<div>
  <%= link_to "Back to chapters", chapters_path %>
</div>

app/views/chapters/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @chapter %>

<div>
  <%= link_to "Edit this chapter", edit_chapter_path(@chapter) %> |
  <%= link_to "Back to chapters", chapters_path %>

  <%= button_to "Destroy this chapter", @chapter, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CalculateDuration</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/series/_form.html.erb
<%= form_with(model: series) do |form| %>
  <% if series.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(series.errors.count, "error") %> prohibited this series from being saved:</h2>

      <ul>
        <% series.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :duration, style: "display: block" %>
    <%= form.number_field :duration %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/series/_series.html.erb
<div id="<%= dom_id series %>">
  <p>
    <strong>Title:</strong>
    <%= series.title %>
  </p>

  <p>
    <strong>Duration:</strong>
    <%= series.duration %>
  </p>

</div>

app/views/series/edit.html.erb
<h1>Editing series</h1>

<%= render "form", series: @series %>

<br>

<div>
  <%= link_to "Show this series", @series %> |
  <%= link_to "Back to series", series_index_path %>
</div>

app/views/series/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Series</h1>

<div id="series">
  <% @series.each do |series| %>
    <%= render series %>
    <p>
      <%= link_to "Show this series", series %>
    </p>
  <% end %>
</div>

<%= link_to "New series", new_series_path %>

app/views/series/new.html.erb
<h1>New series</h1>

<%= render "form", series: @series %>

<br>

<div>
  <%= link_to "Back to series", series_index_path %>
</div>

app/views/series/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @series %>

<div>
  <%= link_to "Edit this series", edit_series_path(@series) %> |
  <%= link_to "Back to series", series_index_path %>

  <%= button_to "Destroy this series", @series, method: :delete %>
</div>